### PR TITLE
Add Target type "ucp" to indicate the type of Context used to interact with a Unified Control Plane endpoint

### PR DESCRIPTION
**Pull request by prkalle**
### What this PR does / why we need it
This PR is to add  "ucp" as new TargetType to indicate the type of Context used to interact with a Unified Control Plane endpoint

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR
Unit test and CI passed

### Release note

```release-note
Add Target type "ucp" to indicate the type of Context used to interact with a Unified Control Plane endpoint
```

### CODE REVIEW

**Review by mpanchajanya — COMMENTED** [review]
Changes looks good. 
nit: Few tests for contexts using new target would be good to ensure everything works as expected

**Comment by prkalle** [comment]
> Changes looks good. nit: Few tests for contexts using new target would be good to ensure everything works as expected especially creating context with ucp target and additional metadata

Thanks @mpanchajanya , updated the PR with the tests

**Review by vuil — APPROVED** [review]
lgtm, thanks!

**Review by mpanchajanya — APPROVED** [review]
Thanks for adding the tests

**Pull request merged**
